### ISSUE TITLE
Still black

### ISSUE THREAD

**Issue by dannogo** [onevcat/Rainbow#12]
My logs are still black. When I set Environment Variable "XcodeColors" to YES, my output is like this: [fg255,0,0;Recognized a double tap[;

**Comment by tangkunyin** [comment]
@dannogo 
Did you installed `XcodeColors` before ? Check you plugins first
---------
However my XcodeColors plugin not install, it still not work. Any one can help.....

**Comment by rob-nash** [comment]
I have set Environment Variable "XcodeColors" to YES in Xcode Version 8.3.2 (8E2002)

The readme doesn't mention anything about installing Xcode colours. Is it a dependency that we need to include ?

```swift
print("Red text".red)
print("Yellow background".onYellow)
print("Light green text on white background".lightGreen.onWhite)
    
print("Underline".underline)
print("Cyan with bold and blinking".cyan.bold.blink)
    
print("Plain text".red.onYellow.bold.clearColor.clearBackgroundColor.clearStyles)
```

```
[fg255,0,0;Red text[;
[bg255,255,0;Yellow background[;
[fg102,255,102;[bg204,204,204;Light green text on white background[;
Underline
[fg0,255,255;Cyan with bold and blinking[;
Plain text
```

**Comment by onevcat** [comment]
Hi,

In Xcode 8, using plugin is prohibited by Apple. That means you can not use things like XcodeColors in Xcode anymore, unless you remove the signature your Xcode (which is not recommended). For more about Xcode 8 plugin support and unsigning Xcode, see [this issue](https://github.com/alcatraz/Alcatraz/issues/475) for more.

I will remove the description about XcodeColors from README file now.

**Comment by tangkunyin** [comment]
@onevcat 所以喵神，这个`Rainbow`在Xcode8以后没法用了？？

**Comment by onevcat** [comment]
Rainbow is mainly built for highlight/text style in terminal and for command line tool written in Swift. It just "happened" to be possible log out styled text with the help of XcodeColors before.
