### ISSUE TITLE
Doesn't work in Xcode 8.3.3 with Swift 3

### ISSUE THREAD

**Issue by DaveChambers** [onevcat/Rainbow#14]
Hi!  

Awesome looking library but for me it doesn't print in colour.  I installed it with Cocoapods.   I must be missing something here.  I'm guessing there are some dependencies I need?  Do I need this:  https://github.com/robbiehanson/XcodeColors ??

Cheers

**Comment by onevcat** [comment]
Xcode 8 does not support third party plugin, so it will not print color message in the Xcode debug console anymore.

**Comment by DaveChambers** [comment]
ok Thanks for the info.
