### ISSUE TITLE
Optional Errors

### ISSUE THREAD

**Issue by anthonycastelli** [onevcat/Rainbow#21]
These two lines return an optional value now, and are throwing the error `Value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?`

I'm not sure what the best way to handle this would be for this project, but in the return line, maybe doing something like `return (codes, text ?? "")`

https://github.com/onevcat/Rainbow/blob/5d5e3d3facd3a46edc260c383f15261b07abcf98/Sources/ModesExtractor.swift#L47

https://github.com/onevcat/Rainbow/blob/5d5e3d3facd3a46edc260c383f15261b07abcf98/Sources/ModesExtractor.swift#L78

**Comment by CodaFi** [comment]
The overload set for that initializer should not be different between the package build and the Xcode build.  Subscript should be giving us a Substring which is trivially convertible to a String without needing optionality - which is what Xcode sees.

**Comment by onevcat** [comment]
@anthonycastelli @CodaFi Thanks for reporting this. I will update the Package.swift soon to solve it.
