### ISSUE TITLE
usage for iOS project

### ISSUE THREAD

**Issue by zolobdz** [onevcat/Rainbow#25]
could this use for iOS project? i use this in my iOS project , and it doesn't work(doesn't show extra console).
what i' done was:
1.add RainbowSwift in my pod file (with right swift version)
2.import RainbowSwift 
3.print("xxxxx".red)

please help

**Comment by xiaohk** [comment]
If you are using Xcode's debug console, you can check out [XcodeColors](https://github.com/robbiehanson/XcodeColors). Rainbow is designed to work on terminal console.

**Comment by onevcat** [comment]
You cannot use XcodeColors or other plugins now on Xcode, unless you resign it. So basically now Rainbow is only for command line apps.
