### ISSUE TITLE
No such module 'Rainbow'

### ISSUE THREAD

**Issue by AdrianBinDC** [onevcat/Rainbow#38]
I followed the directions in the readme file and while I'm able to see Rainbow install when I add the `.package(url: "https://github.com/onevcat/Rainbow", from: "3.0.0")` line to the dependencies array, I get `No such module Rainbow` when I attempt to import it in `main.swift`.

I tried adding it to targets, too, like so:

```
    targets: [
        .target(
            name: "MyCLIUtility",
            dependencies: ["SPMUtility", "Rainbow"]),
        .testTarget(
            name: "MyCLIUtilityTests",
            dependencies: ["MyCLIUtility"]),
    ]
```

What am I missing?

**Comment by onevcat** [comment]
May I know your entire package file?

**Comment by AdrianBinDC** [comment]
Issue resolve :)

In order to get it working, after updating my package dependencies and targets, I ran the following commands after closing Xcode:

1. `swift package update`
2. `swift package generate-xcodeproj`

Then, when I re-opened the project in Xcode, it built without issue. I get spoiled with iOS projects :)

**Comment by onevcat** [comment]
Uploaded a running example and it seems everything goes fine. You can just run `swift run` to confirm it.

[RainbowDemo.zip](https://github.com/onevcat/Rainbow/files/4248012/RainbowDemo.zip)

**Comment by onevcat** [comment]
Oh,

Nice to hear that.
