### ISSUE TITLE
xcode 12 没有效果

### ISSUE THREAD

**Issue by nizenyang** [onevcat/Rainbow#41]
xcode 12不能实现所说的效果，是我没有使用对吗

**Comment by onevcat** [comment]
Xcode 8 以后，Xcode 就不支持完整权限的第三方插件了。这个项目现在是 only for terminal 的。

Readme 里应该也有写

> Although Rainbow is first designed for console output in terminals, you could use it in Xcode with XcodeColors plugin installed too. It will enable color output for better debugging experience in Xcode.
>
> Please notice, after Xcode 8, third party plugins in bundle (like XcodeColors) is not supported anymore. See this.

**Comment by onevcat** [comment]
To prevent misunderstanding, I removed the description of XcodeColors and using in Xcode topics from README.
