### ISSUE TITLE
Empty output in a file

### ISSUE THREAD

**Issue by rsrbk** [onevcat/Rainbow#43]
In my command line tool, when I add `> filename.txt` to output results in a file, it creates an empty file. The output is provided in the console though.

See more details: https://github.com/rsrbk/GoSwifty/issues/3

**Comment by onevcat** [comment]
I cannot reproduce it. See the screenshot below:

![截屏2020-11-02 08 51 39](https://user-images.githubusercontent.com/1019875/97818912-a3247d00-1ce8-11eb-81e8-f3d57aa62e55.png)

Is there a minimal sample that I can use to reproduce this issue? Thanks!

**Comment by rsrbk** [comment]
Hi,
Sorry for bothering, I think we solved the problem , it was not related to Rainbow:)
