### ISSUE TITLE
Add conversion from BackgroundColor to its Color counterpart

### ISSUE THREAD

**Issue by amomchilov** [onevcat/Rainbow#46]
Hey there. I'm trying to build a string similar to a [Powerline prompt](https://github.com/powerline/powerline).

It's a series of segments, separated by a custom powerline triangle glyph. The glyph is coloured predicably: the triangle part of is coloured based on the text colour, and the background is coloured based on the background. But the glyph exists to 
connect two different background colours.

This means you want to set its text colour to the equivalent of the background colour of whats to the left, and the background colour to be equal to the background colour of whats to the right. To achieve this, you need a way of converting a `BackgroundColor` to its `Color` counterpart.

Here's my example:

```swift
import Rainbow

extension BackgroundColor {
	var toTextColor: Color {
		switch self {
		case .black:	return .black
		case .red:		return .red
		case .green:	return .green
		case .yellow:	return .yellow
		case .blue:		return .blue
		case .magenta:	return .magenta
		case .cyan:		return .cyan
		case .white:	return .white
		case .default:	return .default
		}
	}
}

struct Segment {
	let text: String
	let textColor: Color = .default
	let backgroundColor: BackgroundColor
}

extension Collection where Element == Segment {
	func joined() -> String {
		let dummySegment = Segment(text: "", backgroundColor: .default)
		
		let strings = zip(self, self.dropFirst() + [dummySegment]).map { current, next -> String in
			let separator = "".applyingCodes(current.backgroundColor.toTextColor, next.backgroundColor)
			let text = current.text.applyingCodes(current.textColor, current.backgroundColor)
			return text + separator
		}
		
		return strings.joined()
	}
}

let segments = [
	Segment(text: "abc", backgroundColor: .red),
	Segment(text: "def", backgroundColor: .green),
	Segment(text: "ghi", backgroundColor: .blue),
]

let result = segments.joined() + " The rest of the message"

print("before\n")
print(result)
print("\nafter")
```

Output (rendered in [SF mono nerd font](https://github.com/epk/SF-Mono-Nerd-Font):

![image](https://user-images.githubusercontent.com/5703449/107309553-a0a89080-6a58-11eb-8b41-d0e9bc9c69de.png)

I wanted to contribute the implementation of `toTextColor`, because I think it might be useful to others. The reverse direction might also be useful, though there are more `Color`s than can map onto `BackgroundColor`s, so its unclear how to handle the unmappable cases (make the computed property optional and return `nil`?)

Do you think this would be useful for me to contribute?

If so, how do you think I should write the test for it?

**Comment by onevcat** [comment]
Hi,

Thanks for opening this. I think it would be very useful!

For the lack of background color (you may notice that there is no light version of background colors), actually, they should be also supported. It is me to blame since I was too lazy to add them.

Meanwhile, I am working on some big changes for #45 right now, and maybe introducing some break changes to the current API. I suggest you can wait for a while before I have a chance to finish them. I will append more comments here when it is prepared so we can continue this conversion helper!

**Comment by amomchilov** [comment]
Excellent, thanks! Keep me posted :)

**Comment by onevcat** [comment]
Done.  See [the tests](https://github.com/onevcat/Rainbow/pull/54/files#diff-a39a675f9ea07fed6381d6b0e648c418b17d8f107bd682de2596e0a521886043) for using cases.

**Comment by onevcat** [comment]
A new tag will be applied later. Before that, I have some other plans for this library. Before all prepared, if you need this API, feel free to pin it to the master branch for a while. :)

**Comment by amomchilov** [comment]
Awesome, thanks!

**Comment by onevcat** [comment]
Version 4.0 was just released and containing this change.
