### ISSUE TITLE
Cocopod 1.1 doesn't output colors

### ISSUE THREAD

**Issue by world** [onevcat/Rainbow#6]
Using Xcode 7.3 cocopods. I added Rainbow in the Podfile per your README. I also remembered to import RaindobowSwift (vs Rainbow). Now, when I try to use it, type-ahead shows me the colors so I know the class is being read. However, no text comes out colored. (ie `print("hello myself".red)` just prints "hello myself" in the normal console color. I feel like xcode is somehow overriding the coloring maybe. 

Ideas? 

PS I am in a bridged obj-c/swift project if that's a clue. However, I am only trying this from the Swift side without luck...

**Comment by onevcat** [comment]
Did you try to output the string into a console (like Terminal or iTerm) or just use it inside the Xcode?

If you are using it in Xcode, you may need an Xcode plugin to enable the color rendering inside Xcode's console panel. You could find more in the first paragraph and the "Question" section in the read me file.

**Comment by world** [comment]
Thank you for your help thus far:

1. I am only using it inside Xcode. No 3rd party console.
2. I am not using XCodeColors plugin, so why do I need the environment variable?

**Comment by onevcat** [comment]
The console of Xcode does not support colorize the log by default, so you need a third party plugin (XCodeColors) to render colorful output in Xcode.

**Comment by Maxatma** [comment]
It just doesn't work, idk problem in pod or in XcodeColor plugin. Xcode Version 7.3.1, no 3rd party consoles.
