### ISSUE TITLE
Segment group doesn't work for `backgroundColor` and `styles`.

### ISSUE THREAD

**Issue by xingheng** [onevcat/Rainbow#60]
Wei, thanks for your contribution to this project, my [new tool](https://github.com/CLILogger/CLILogger) relies on it strongly.

After upgrading to the new version 4.0.0, I use the following code to join a colorful message in terminal console, but got something unexpected results:

```swift
import RainbowSwift

let entry = Rainbow.Entry(
    segments: [
        .init(text: "Hello ", color: .named(.magenta)),
        .init(text: "Rainbow ", color: .bit8(214), backgroundColor: .named(.black), styles: [.underline]),
        .init(text: "Hello ", color: .named(.magenta)/*, backgroundColor: .named(.default)*/),  // Comment 1
        .init(text: "again", color: .named(.magenta), backgroundColor: .named(.red)/*, styles: [.default]*/),  // Comment 2
    ]
)
print(Rainbow.generateString(for: entry))
```
It shows the black background and styles from the second segment on the second `Hello`, this is weird, the underline style also affects to the last segment:
<img width="289" alt="1" src="https://user-images.githubusercontent.com/2891714/130357822-21fdaa2e-714d-4a0c-a290-50f4e760fab3.png">

If I uncomment the `Comment 1` only:
<img width="264" alt="2" src="https://user-images.githubusercontent.com/2891714/130357953-c22dadcf-5745-4f95-8b76-cb3ab58c3145.png">

If I uncoment the `Comment 2` only:
<img width="277" alt="3" src="https://user-images.githubusercontent.com/2891714/130357970-c4c80f1a-5c9e-4016-880a-ccfd79cf50a2.png">

Uncomment both:
<img width="276" alt="4" src="https://user-images.githubusercontent.com/2891714/130357987-89ffd96a-69f6-4fc2-9f43-cd44a31ed820.png">

I really don't know how to explain them even after trying to look into the `Rainbow` inside, please confirm is it a bug or how should I use the `Segment`.
Thanks!

**Comment by onevcat** [comment]
A lack of color or style now is not meaning "reset to default", but inherit the one set by the previous segment, until you give it another explicit setting. This is how the ANSI console escape works, but I am now a bit not sure if it is still good for `Rainbow.Entry(segments:)`. From the aspect of OOP, it is a bug and I guess we need to add a reset command on each segment. But it outputs a more complicated result. So here is a trade-off and more careful consideration. I would need some time to think about it.

For a quick around, I believe you can explicitly set `backgroundColor: .named(.default)` and `styles: [.default]` to every segment to reset any unnecessary format.

**Comment by xingheng** [comment]
Got it, I'll drop to join the results of `applyingColor` serial method manually for safe. Thanks for your quick response.
