### ISSUE TITLE
Style doesn't get reset for substring

### ISSUE THREAD

**Issue by Snowy1803** [onevcat/Rainbow#61]
Hello,

This simple code has an unexpected result:
```swift
print(("a" + "b".underline + "c").lightGreen)
```
I would expect the whole string to be in green, and the `b` only to be underlined, however the underlining doesn't get reset, so the `c` gets underlined too!

Expected result: `\e[92ma\e[92;4mb\e[0;92mc\e[0m`
Actual result: `\e[92ma\e[92;4mb\e[92mc\e[0m`
![abc with both b and c underlined](https://user-images.githubusercontent.com/7999977/134403922-00702889-4dfc-4f01-8582-95d20a6c4a28.png)

This happens with all styles when applied to a substring where a foreground color is inherited.

**Comment by onevcat** [comment]
Duplicated to #60, should be fixed in #62

**Comment by onevcat** [comment]
Merged and this should be fixed.
