### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [onevcat/Rainbow#8]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by onevcat** [comment]
Version 2.0.0 is released, with Swift 3 supported.

**Comment by frogcjn** [comment]
@Ifarah, how to use it with Xocde 8? Since Xocde 8 kills non-official extension, thus Rainbow cannot work with XcodeColors

**Comment by onevcat** [comment]
You cannot use it with Xcode plugins unless you [unsign](https://github.com/alcatraz/Alcatraz/issues/475) your Xcode.
